// Conversion definitions adapted from units_converter 2.0.1 (MIT), Damiano Ferrari.
export const categories = [
  {
    id: "length",
    name: "Length",
    icon: "ruler",
    description: "Every distance, from tiny to astronomical.",
    units: [
      {
        id: "meters",
        factor: 1,
        offset: 0,
        symbol: "m",
        name: "Meters",
        labelKey: "meters",
      },
      {
        id: "centimeters",
        factor: 0.01,
        offset: 0,
        symbol: "cm",
        name: "Centimeters",
        labelKey: "centimeters",
      },
      {
        id: "inches",
        factor: 0.025400000000000002,
        offset: 0.0,
        symbol: "in",
        name: "Inches",
        labelKey: "inches",
      },
      {
        id: "feet",
        factor: 0.3048,
        offset: 0.0,
        symbol: "ft",
        name: "Feet",
        labelKey: "feet",
      },
      {
        id: "feetUs",
        factor: 0.30480060960000005,
        offset: 0.0,
        symbol: "ft(US survey)",
        name: "Feet (US survey)",
        labelKey: "feetUsSurvey",
      },
      {
        id: "mils",
        factor: 2.5400000000000004e-5,
        offset: 0.0,
        symbol: "",
        name: "Mils",
        labelKey: "mils",
      },
      {
        id: "nauticalMiles",
        factor: 1852.0,
        offset: 0,
        symbol: "M",
        name: "Nautical miles",
        labelKey: "nauticalMiles",
      },
      {
        id: "yards",
        factor: 0.9144,
        offset: 0,
        symbol: "yd",
        name: "Yards",
        labelKey: "yards",
      },
      {
        id: "miles",
        factor: 1609.344,
        offset: 0.0,
        symbol: "mi",
        name: "Miles",
        labelKey: "miles",
      },
      {
        id: "millimeters",
        factor: 0.001,
        offset: 0,
        symbol: "mm",
        name: "Millimeters",
        labelKey: "millimeters",
      },
      {
        id: "micrometers",
        factor: 1e-6,
        offset: 0,
        symbol: "µm",
        name: "Micrometers",
        labelKey: "micrometers",
      },
      {
        id: "nanometers",
        factor: 1e-9,
        offset: 0,
        symbol: "nm",
        name: "Nanometers",
        labelKey: "nanometers",
      },
      {
        id: "angstroms",
        factor: 1e-10,
        offset: 0,
        symbol: "Å",
        name: "Ångström",
        labelKey: "angstroms",
      },
      {
        id: "picometers",
        factor: 1e-12,
        offset: 0,
        symbol: "pm",
        name: "Picometers",
        labelKey: "picometers",
      },
      {
        id: "kilometers",
        factor: 1000.0,
        offset: 0,
        symbol: "km",
        name: "Kilometers",
        labelKey: "kilometers",
      },
      {
        id: "astronomicalUnits",
        factor: 149597870700.0,
        offset: 0.0,
        symbol: "au",
        name: "Astronomical Units",
        labelKey: "astronomicalUnits",
      },
      {
        id: "lightYears",
        factor: 9460730472580800,
        offset: 0.0,
        symbol: "ly",
        name: "Light-years",
        labelKey: "lightYears",
      },
      {
        id: "parsec",
        factor: 3.085677581491367e16,
        offset: 0.0,
        symbol: "pc",
        name: "Parsec",
        labelKey: "parsec",
      },
    ],
  },
  {
    id: "area",
    name: "Area",
    icon: "area",
    description: "Find the right measure for your space.",
    units: [
      {
        id: "squareMeters",
        factor: 1,
        offset: 0,
        symbol: "m²",
        name: "Square Meters",
        labelKey: "squareMeters",
      },
      {
        id: "squareCentimeters",
        factor: 0.0001,
        offset: 0,
        symbol: "cm²",
        name: "Square Centimeters",
        labelKey: "squareCentimeters",
      },
      {
        id: "squareInches",
        factor: 0.00064516,
        offset: 0.0,
        symbol: "in²",
        name: "Square Inches",
        labelKey: "squareInches",
      },
      {
        id: "squareFeet",
        factor: 0.09290303999999999,
        offset: 0.0,
        symbol: "ft²",
        name: "Square Feet",
        labelKey: "squareFeet",
      },
      {
        id: "squareFeetUs",
        factor: 0.0929034116125316,
        offset: 0.0,
        symbol: "ft² (US survey)",
        name: "Square Feet (US survey)",
        labelKey: "squareFeetUsSurvey",
      },
      {
        id: "squareMillimeters",
        factor: 1e-6,
        offset: 0,
        symbol: "mm²",
        name: "Square Millimeters",
        labelKey: "squareMillimeters",
      },
      {
        id: "hectares",
        factor: 10000.0,
        offset: 0,
        symbol: "ha",
        name: "Hectares",
        labelKey: "hectares",
      },
      {
        id: "squareKilometers",
        factor: 1000000.0,
        offset: 0,
        symbol: "km²",
        name: "Square Kilometers",
        labelKey: "squareKilometers",
      },
      {
        id: "squareYard",
        factor: 0.83612736,
        offset: 0,
        symbol: "yd²",
        name: "Square Yard",
        labelKey: "squareYard",
      },
      {
        id: "squareMiles",
        factor: 2589988.110336,
        offset: 0.0,
        symbol: "mi²",
        name: "Square Miles",
        labelKey: "squareMiles",
      },
      {
        id: "acres",
        factor: 4046.8564224,
        offset: 0.0,
        symbol: "ac",
        name: "Acres",
        labelKey: "acres",
      },
      {
        id: "are",
        factor: 100.0,
        offset: 0,
        symbol: "a",
        name: "Are",
        labelKey: "are",
      },
    ],
  },
  {
    id: "volume",
    name: "Volume",
    icon: "beaker",
    description: "A little clarity for every drop.",
    units: [
      {
        id: "cubicMeters",
        factor: 1,
        offset: 0,
        symbol: "m³",
        name: "Cubic Meters",
        labelKey: "cubicMeters",
      },
      {
        id: "liters",
        factor: 0.001,
        offset: 0,
        symbol: "l",
        name: "Liters",
        labelKey: "liters",
      },
      {
        id: "imperialGallons",
        factor: 0.004546090000000001,
        offset: 0.0,
        symbol: "imp gal",
        name: "Imperial gallons",
        labelKey: "imperialGallons",
      },
      {
        id: "usGallons",
        factor: 0.003785411784,
        offset: 0.0,
        symbol: "US gal",
        name: "US Gallons",
        labelKey: "usGallons",
      },
      {
        id: "imperialPints",
        factor: 0.0005682612500000001,
        offset: 0.0,
        symbol: "imp pt",
        name: "Imperial Pints",
        labelKey: "imperialPints",
      },
      {
        id: "imperialFluidOunces",
        factor: 2.8413062500000008e-5,
        offset: 0.0,
        symbol: "imp fl oz",
        name: "Imperial Fluid Ounces",
        labelKey: "imperialFluidOunces",
      },
      {
        id: "imperialGill",
        factor: 0.00014206531250000003,
        offset: 0.0,
        symbol: "Imp. gi.",
        name: "Imperial Gill",
        labelKey: "imperialGill",
      },
      {
        id: "usPints",
        factor: 0.000473176473,
        offset: 0.0,
        symbol: "US pt",
        name: "US Pints",
        labelKey: "usPints",
      },
      {
        id: "usFluidOunces",
        factor: 2.95735295625e-5,
        offset: 0.0,
        symbol: "US fl oz",
        name: "US Fluid Ounces",
        labelKey: "usFluidOunces",
      },
      {
        id: "usGill",
        factor: 0.00011829411825,
        offset: 0.0,
        symbol: "US. liq. gi",
        name: "US Gill",
        labelKey: "usGill",
      },
      {
        id: "milliliters",
        factor: 1e-6,
        offset: 0.0,
        symbol: "ml",
        name: "Milliliters",
        labelKey: "milliliters",
      },
      {
        id: "tablespoonsUs",
        factor: 1.48e-5,
        offset: 0.0,
        symbol: "tbsp.",
        name: "Tablespoons US",
        labelKey: "tablespoonUs",
      },
      {
        id: "australianTablespoons",
        factor: 1.9999999999999998e-5,
        offset: 0.0,
        symbol: "tbsp.",
        name: "Australian Tablespoons",
        labelKey: "tablespoonAustralian",
      },
      {
        id: "cups",
        factor: 0.00023999999999999998,
        offset: 0.0,
        symbol: "cup",
        name: "Cups",
        labelKey: "cups",
      },
      {
        id: "cubicCentimeters",
        factor: 1e-6,
        offset: 0,
        symbol: "cm³",
        name: "Cubic Centimeters",
        labelKey: "cubicCentimeters",
      },
      {
        id: "cubicInches",
        factor: 1.6387064e-5,
        offset: 0.0,
        symbol: "in³",
        name: "Cubic Inches",
        labelKey: "cubicInches",
      },
      {
        id: "cubicFeet",
        factor: 0.028316846591999997,
        offset: 0.0,
        symbol: "ft³",
        name: "Cubic Feet",
        labelKey: "cubicFeet",
      },
      {
        id: "cubicMillimeters",
        factor: 1e-9,
        offset: 0,
        symbol: "mm³",
        name: "Cubic Millimeters",
        labelKey: "cubicMillimeters",
      },
    ],
  },
  {
    id: "currencies",
    name: "Currency",
    icon: "currency",
    description: "A world of currencies. One clear answer.",
    units: [
      {
        id: "EUR",
        name: "Euro",
        symbol: "EUR",
        labelKey: "EUR",
      },
      {
        id: "CAD",
        name: "Canadian dollar",
        symbol: "CAD",
        labelKey: "CAD",
      },
      {
        id: "HKD",
        name: "Hong Kong dollar",
        symbol: "HKD",
        labelKey: "HKD",
      },
      {
        id: "PHP",
        name: "Philippine peso",
        symbol: "PHP",
        labelKey: "PHP",
      },
      {
        id: "DKK",
        name: "Danish krone",
        symbol: "DKK",
        labelKey: "DKK",
      },
      {
        id: "NZD",
        name: "New Zealand dollar",
        symbol: "NZD",
        labelKey: "NZD",
      },
      {
        id: "CNY",
        name: "Chinese yuan",
        symbol: "CNY",
        labelKey: "CNY",
      },
      {
        id: "AUD",
        name: "Australian dollar",
        symbol: "AUD",
        labelKey: "AUD",
      },
      {
        id: "RON",
        name: "Romanian leu",
        symbol: "RON",
        labelKey: "RON",
      },
      {
        id: "SEK",
        name: "Swedish krona",
        symbol: "SEK",
        labelKey: "SEK",
      },
      {
        id: "IDR",
        name: "Indonesian rupiah",
        symbol: "IDR",
        labelKey: "IDR",
      },
      {
        id: "INR",
        name: "Indian rupee",
        symbol: "INR",
        labelKey: "INR",
      },
      {
        id: "BRL",
        name: "Brazilian real",
        symbol: "BRL",
        labelKey: "BRL",
      },
      {
        id: "USD",
        name: "US dollar",
        symbol: "USD",
        labelKey: "USD",
      },
      {
        id: "ILS",
        name: "Israeli new shekel",
        symbol: "ILS",
        labelKey: "ILS",
      },
      {
        id: "JPY",
        name: "Japanese yen",
        symbol: "JPY",
        labelKey: "JPY",
      },
      {
        id: "THB",
        name: "Thai baht",
        symbol: "THB",
        labelKey: "THB",
      },
      {
        id: "CHF",
        name: "Swiss franc",
        symbol: "CHF",
        labelKey: "CHF",
      },
      {
        id: "CZK",
        name: "Czech koruna",
        symbol: "CZK",
        labelKey: "CZK",
      },
      {
        id: "MYR",
        name: "Malaysian ringgit",
        symbol: "MYR",
        labelKey: "MYR",
      },
      {
        id: "TRY",
        name: "Turkish lira",
        symbol: "TRY",
        labelKey: "TRY",
      },
      {
        id: "MXN",
        name: "Mexican peso",
        symbol: "MXN",
        labelKey: "MXN",
      },
      {
        id: "NOK",
        name: "Norwegian krone",
        symbol: "NOK",
        labelKey: "NOK",
      },
      {
        id: "HUF",
        name: "Hungarian forint",
        symbol: "HUF",
        labelKey: "HUF",
      },
      {
        id: "ZAR",
        name: "South African rand",
        symbol: "ZAR",
        labelKey: "ZAR",
      },
      {
        id: "SGD",
        name: "Singapore dollar",
        symbol: "SGD",
        labelKey: "SGD",
      },
      {
        id: "GBP",
        name: "British pound",
        symbol: "GBP",
        labelKey: "GBP",
      },
      {
        id: "KRW",
        name: "South Korean won",
        symbol: "KRW",
        labelKey: "KRW",
      },
      {
        id: "PLN",
        name: "Polish złoty",
        symbol: "PLN",
        labelKey: "PLN",
      },
      {
        id: "BGN",
        name: "Bulgarian lev",
        symbol: "BGN",
        labelKey: "BGN",
      },
      {
        id: "ISK",
        name: "Icelandic króna",
        symbol: "ISK",
        labelKey: "ISK",
      },
    ],
  },
  {
    id: "time",
    name: "Time",
    icon: "clock",
    description: "Make every moment add up.",
    units: [
      {
        id: "seconds",
        factor: 1,
        offset: 0,
        symbol: "s",
        name: "Seconds",
        labelKey: "seconds",
      },
      {
        id: "deciseconds",
        factor: 0.1,
        offset: 0,
        symbol: "ds",
        name: "Deciseconds",
        labelKey: "deciseconds",
      },
      {
        id: "centiseconds",
        factor: 0.01,
        offset: 0,
        symbol: "cs",
        name: "Centiseconds",
        labelKey: "centiseconds",
      },
      {
        id: "milliseconds",
        factor: 0.001,
        offset: 0,
        symbol: "ms",
        name: "Milliseconds",
        labelKey: "milliseconds",
      },
      {
        id: "microseconds",
        factor: 1e-6,
        offset: 0,
        symbol: "µs",
        name: "Microseconds",
        labelKey: "microseconds",
      },
      {
        id: "nanoseconds",
        factor: 1e-9,
        offset: 0,
        symbol: "ns",
        name: "Nanoseconds",
        labelKey: "nanoseconds",
      },
      {
        id: "minutes",
        factor: 60.0,
        offset: 0,
        symbol: "min",
        name: "Minutes",
        labelKey: "minutes",
      },
      {
        id: "hours",
        factor: 3600.0,
        offset: 0.0,
        symbol: "h",
        name: "Hours",
        labelKey: "hours",
      },
      {
        id: "days",
        factor: 86400.0,
        offset: 0.0,
        symbol: "d",
        name: "Days",
        labelKey: "days",
      },
      {
        id: "weeks",
        factor: 604800.0,
        offset: 0.0,
        symbol: "",
        name: "Weeks",
        labelKey: "weeks",
      },
      {
        id: "years365",
        factor: 31536000.0,
        offset: 0.0,
        symbol: "a",
        name: "Years (365)",
        labelKey: "years",
      },
      {
        id: "lustrum",
        factor: 157680000.0,
        offset: 0.0,
        symbol: "",
        name: "Lustrum",
        labelKey: "lustrum",
      },
      {
        id: "decades",
        factor: 315360000.0,
        offset: 0.0,
        symbol: "",
        name: "Decades",
        labelKey: "decades",
      },
      {
        id: "centuries",
        factor: 3153600000.0,
        offset: 0.0,
        symbol: "c.",
        name: "Centuries",
        labelKey: "centuries",
      },
      {
        id: "millennium",
        factor: 31536000000.0,
        offset: 0.0,
        symbol: "",
        name: "Millennium",
        labelKey: "millennium",
      },
    ],
  },
  {
    id: "temperature",
    name: "Temperature",
    icon: "thermometer",
    description: "A fresh perspective on degrees.",
    units: [
      {
        id: "fahrenheit",
        factor: 1,
        offset: 0,
        symbol: "°F",
        name: "Fahrenheit",
        labelKey: "fahrenheit",
      },
      {
        id: "celsius",
        factor: 1.8,
        offset: 32.0,
        symbol: "°C",
        name: "Celsius (Centigrade)",
        labelKey: "celsius",
      },
      {
        id: "kelvin",
        factor: 1.8,
        offset: -459.66999999999996,
        symbol: "K",
        name: "Kelvin",
        labelKey: "kelvin",
      },
      {
        id: "reamur",
        factor: 2.25,
        offset: 32.0,
        symbol: "°Re",
        name: "Reamur",
        labelKey: "reamur",
      },
      {
        id: "romer",
        factor: 3.4285714285714284,
        offset: 6.285714285714285,
        symbol: "°Rø",
        name: "Rømer",
        labelKey: "romer",
      },
      {
        id: "delisle",
        factor: -1.2,
        offset: 212.0,
        symbol: "°De",
        name: "Delisle",
        labelKey: "delisle",
      },
      {
        id: "rankine",
        factor: 1,
        offset: -459.67,
        symbol: "°R",
        name: "Rankine",
        labelKey: "rankine",
      },
    ],
  },
  {
    id: "speed",
    name: "Speed",
    icon: "gauge",
    description: "From a gentle pace to the speed of light.",
    units: [
      {
        id: "metersPerSecond",
        factor: 1,
        offset: 0,
        symbol: "m/s",
        name: "Meters per Second",
        labelKey: "metersSecond",
      },
      {
        id: "kilometersPerHour",
        factor: 0.2777777777777778,
        offset: 0,
        symbol: "km/h",
        name: "Kilometers per Hour",
        labelKey: "kilometersHour",
      },
      {
        id: "milesPerHour",
        factor: 0.44704000000000005,
        offset: 0.0,
        symbol: "mi/h",
        name: "Miles per Hour",
        labelKey: "milesHour",
      },
      {
        id: "knots",
        factor: 0.5144444444444445,
        offset: 0.0,
        symbol: "kts",
        name: "Knots",
        labelKey: "knots",
      },
      {
        id: "minutesPerKilometer",
        factor: 16.666666666666668,
        offset: 0.0,
        reciprocal: true,
        symbol: "min/km",
        name: "Minutes per Kilometer",
        labelKey: "minutesPerKilometer",
      },
      {
        id: "feetsPerSecond",
        factor: 0.3048,
        offset: 0,
        symbol: "ft/s",
        name: "Feet per Second",
        labelKey: "feetSecond",
      },
    ],
  },
  {
    id: "mass",
    name: "Mass",
    icon: "weight",
    description: "Find your balance, in any unit.",
    units: [
      {
        id: "grams",
        factor: 1,
        offset: 0,
        symbol: "g",
        name: "Grams",
        labelKey: "grams",
      },
      {
        id: "ettograms",
        factor: 100.0,
        offset: 0,
        symbol: "hg",
        name: "Ettograms",
        labelKey: "ettograms",
      },
      {
        id: "kilograms",
        factor: 1000.0,
        offset: 0,
        symbol: "kg",
        name: "Kilograms",
        labelKey: "kilograms",
      },
      {
        id: "pounds",
        factor: 453.59237,
        offset: 0.0,
        symbol: "lb",
        name: " Pounds",
        labelKey: "pounds",
      },
      {
        id: "ounces",
        factor: 28.349523125,
        offset: 0.0,
        symbol: "oz",
        name: "Ounces",
        labelKey: "ounces",
      },
      {
        id: "stones",
        factor: 6350.293180000001,
        offset: 0.0,
        symbol: "st.",
        name: "Stones",
        labelKey: "stones",
      },
      {
        id: "quintals",
        factor: 100000.0,
        offset: 0,
        symbol: "",
        name: "Quintals",
        labelKey: "quintals",
      },
      {
        id: "tons",
        factor: 1000000.0,
        offset: 0,
        symbol: "t",
        name: "Tons",
        labelKey: "tons",
      },
      {
        id: "centigrams",
        factor: 0.01,
        offset: 0,
        symbol: "cg",
        name: "Centigrams",
        labelKey: "centigrams",
      },
      {
        id: "milligrams",
        factor: 0.001,
        offset: 0,
        symbol: "mg",
        name: "Milligrams",
        labelKey: "milligrams",
      },
      {
        id: "uma",
        factor: 1.660539e-24,
        offset: 0,
        symbol: "u",
        name: "Unified atomic mass unit",
        labelKey: "uma",
      },
      {
        id: "carats",
        factor: 0.2,
        offset: 0,
        symbol: "ct",
        name: "Carats",
        labelKey: "carats",
      },
      {
        id: "pennyweights",
        factor: 1.55517384,
        offset: 0,
        symbol: "dwt",
        name: "Pennyweights",
        labelKey: "pennyweights",
      },
      {
        id: "troyOunces",
        factor: 31.1034768,
        offset: 0.0,
        symbol: "oz t",
        name: "Troy ounces",
        labelKey: "troyOunces",
      },
    ],
  },
  {
    id: "force",
    name: "Force",
    icon: "bolt",
    description: "Put a number to the push and pull.",
    units: [
      {
        id: "newton",
        factor: 1,
        offset: 0,
        symbol: "N",
        name: "Newton",
        labelKey: "newton",
      },
      {
        id: "dyne",
        factor: 1e-5,
        offset: 0,
        symbol: "dyn",
        name: "Dyne",
        labelKey: "dyne",
      },
      {
        id: "poundForce",
        factor: 4.4482216152605,
        offset: 0,
        symbol: "lbf",
        name: "Pound-force",
        labelKey: "poundForce",
      },
      {
        id: "kilogramForce",
        factor: 9.80665,
        offset: 0,
        symbol: "kgf",
        name: "Kilogram-force",
        labelKey: "kilogramForce",
      },
      {
        id: "poundal",
        factor: 0.138254954376,
        offset: 0,
        symbol: "pdl",
        name: "Poundal",
        labelKey: "poundal",
      },
    ],
  },
  {
    id: "fuelConsumption",
    name: "Fuel consumption",
    icon: "fuel",
    description: "Go further with the right numbers.",
    units: [
      {
        id: "kilometersPerLiter",
        factor: 1,
        offset: 0,
        symbol: "km/l",
        name: "Kilometers per liter",
        labelKey: "kilometersLiter",
      },
      {
        id: "litersPer100km",
        factor: 100.0,
        offset: 0,
        reciprocal: true,
        symbol: "l/100km",
        name: "Liters per 100 km",
        labelKey: "liters100km",
      },
      {
        id: "milesPerUsGallon",
        factor: 0.425143707430272,
        offset: 0,
        symbol: "mpg US",
        name: "Miles per US Gallon",
        labelKey: "milesUsGallon",
      },
      {
        id: "milesPerImperialGallon",
        factor: 0.3540061899346471,
        offset: 0,
        symbol: "mpg UK",
        name: "Miles per imperial Gallon",
        labelKey: "milesImperialGallon",
      },
    ],
  },
  {
    id: "numeralSystems",
    name: "Number systems",
    icon: "code",
    description: "Speak the language of numbers.",
    units: [
      {
        id: "decimal",
        name: "Decimal",
        symbol: "Base 10",
        base: 10,
        labelKey: "decimal",
      },
      {
        id: "hexadecimal",
        name: "Hexadecimal",
        symbol: "Base 16",
        base: 16,
        labelKey: "hexadecimal",
      },
      {
        id: "octal",
        name: "Octal",
        symbol: "Base 8",
        base: 8,
        labelKey: "octal",
      },
      {
        id: "binary",
        name: "Binary",
        symbol: "Base 2",
        base: 2,
        labelKey: "binary",
      },
    ],
  },
  {
    id: "pressure",
    name: "Pressure",
    icon: "gauge",
    description: "Make sense of the pressure.",
    units: [
      {
        id: "pascal",
        factor: 1,
        offset: 0,
        symbol: "Pa",
        name: "Pascal",
        labelKey: "pascal",
      },
      {
        id: "bar",
        factor: 100000.0,
        offset: 0,
        symbol: "bar",
        name: "Bar",
        labelKey: "bar",
      },
      {
        id: "millibar",
        factor: 100.0,
        offset: 0.0,
        symbol: "mbar",
        name: "Millibar",
        labelKey: "millibar",
      },
      {
        id: "atmosphere",
        factor: 101325.0,
        offset: 0,
        symbol: "atm",
        name: "Atmosphere",
        labelKey: "atmosphere",
      },
      {
        id: "psi",
        factor: 6894.757293168,
        offset: 0,
        symbol: "psi",
        name: "Pounds per square inch",
        labelKey: "psi",
      },
      {
        id: "torr",
        factor: 133.322368421,
        offset: 0,
        symbol: "torr",
        name: "Torricelli",
        labelKey: "torr",
      },
      {
        id: "inchOfMercury",
        factor: 3386.3881578933997,
        offset: 0.0,
        symbol: "inHg",
        name: "Inches of mercury",
        labelKey: "inchesOfMercury",
      },
      {
        id: "hectoPascal",
        factor: 100.0,
        offset: 0,
        symbol: "hPa",
        name: "Hectopascal",
        labelKey: "hectoPascal",
      },
    ],
  },
  {
    id: "energy",
    name: "Energy",
    icon: "bolt",
    description: "Understand the energy behind it all.",
    units: [
      {
        id: "joules",
        factor: 1,
        offset: 0,
        symbol: "J",
        name: "Joule",
        labelKey: "joule",
      },
      {
        id: "calories",
        factor: 4.1867999409,
        offset: 0,
        symbol: "cal",
        name: "Calories",
        labelKey: "calories",
      },
      {
        id: "kilocalories",
        factor: 4186.7999409,
        offset: 0.0,
        symbol: "kcal",
        name: "Kilocalories",
        labelKey: "kilocalories",
      },
      {
        id: "kilowattHours",
        factor: 3600000.0,
        offset: 0,
        symbol: "kwh",
        name: "Kilowatt hour",
        labelKey: "kilowattHour",
      },
      {
        id: "electronvolts",
        factor: 1.60217646e-19,
        offset: 0,
        symbol: "eV",
        name: "Electron volt",
        labelKey: "electronvolt",
      },
      {
        id: "energyFootPound",
        factor: 1.3558179483314003,
        offset: 0,
        symbol: "ft⋅lbf",
        name: "Foot pound",
        labelKey: "footPound",
      },
    ],
  },
  {
    id: "power",
    name: "Power",
    icon: "plug",
    description: "Small watts. Big possibilities.",
    units: [
      {
        id: "watt",
        factor: 1,
        offset: 0,
        symbol: "W",
        name: "Watt",
        labelKey: "watt",
      },
      {
        id: "milliwatt",
        factor: 0.001,
        offset: 0,
        symbol: "mW",
        name: "Milliwatt",
        labelKey: "milliwatt",
      },
      {
        id: "kilowatt",
        factor: 1000.0,
        offset: 0,
        symbol: "kW",
        name: "Kilowatt",
        labelKey: "kilowatt",
      },
      {
        id: "megawatt",
        factor: 1000000.0,
        offset: 0,
        symbol: "MW",
        name: "Megawatt",
        labelKey: "megawatt",
      },
      {
        id: "gigawatt",
        factor: 1000000000.0,
        offset: 0,
        symbol: "GW",
        name: "GigaWatt",
        labelKey: "gigawatt",
      },
      {
        id: "europeanHorsePower",
        factor: 735.49875,
        offset: 0,
        symbol: "hp(M)",
        name: "European horsepower",
        labelKey: "europeanHorsePower",
      },
      {
        id: "imperialHorsePower",
        factor: 745.69987158,
        offset: 0,
        symbol: "hp(I)",
        name: "Imperial horsepower",
        labelKey: "imperialHorsePower",
      },
    ],
  },
  {
    id: "angle",
    name: "Angles",
    icon: "angle",
    description: "See things from a different angle.",
    units: [
      {
        id: "degree",
        factor: 1,
        offset: 0,
        symbol: "°",
        name: "Degree",
        labelKey: "degree",
      },
      {
        id: "minutes",
        factor: 0.016666666666666666,
        offset: 0,
        symbol: "",
        name: "Minutes",
        labelKey: "minutesDegree",
      },
      {
        id: "seconds",
        factor: 0.0002777777777777778,
        offset: 0,
        symbol: "",
        name: "Seconds",
        labelKey: "secondsDegree",
      },
      {
        id: "radians",
        factor: 57.29577951308232,
        offset: 0,
        symbol: "rad",
        name: "Radians",
        labelKey: "radiansDegree",
      },
      {
        id: "turns",
        name: "Turns",
        symbol: "turn",
        factor: 360,
        offset: 0,
        labelKey: "turns",
      },
      {
        id: "gradians",
        name: "Gradians",
        symbol: "gon",
        factor: 0.9,
        offset: 0,
        labelKey: "gradians",
      },
    ],
  },
  {
    id: "shoeSize",
    name: "Shoe size",
    icon: "shoe",
    description: "Find your fit, wherever you go.",
    units: [
      {
        id: "centimeters",
        factor: 1,
        offset: 0,
        symbol: "cm",
        name: "Centimeters",
        labelKey: "centimeters",
      },
      {
        id: "euChina",
        factor: 0.6666666666666666,
        offset: -1.5,
        symbol: "",
        name: "EU & China",
        labelKey: "euChina",
      },
      {
        id: "inches",
        factor: 2.54,
        offset: 0,
        symbol: "in",
        name: "Inches",
        labelKey: "inches",
      },
      {
        id: "ukIndiaChild",
        factor: 0.8466666666666667,
        offset: 8.466666666666667,
        symbol: "",
        name: "UK & India - Child",
        labelKey: "ukIndiaChild",
      },
      {
        id: "ukIndiaMan",
        factor: 0.8466666666666667,
        offset: 19.473333333333333,
        symbol: "",
        name: "UK & India - Man",
        labelKey: "ukIndiaMan",
      },
      {
        id: "ukIndiaWoman",
        factor: 0.8466666666666667,
        offset: 19.896666666666665,
        symbol: "",
        name: "UK & India - Woman",
        labelKey: "ukIndiaWoman",
      },
      {
        id: "usaCanadaChild",
        factor: 0.8466666666666667,
        offset: 13.828888888888889,
        symbol: "",
        name: "USA & Canada - Child",
        labelKey: "usaCanadaChild",
      },
      {
        id: "usaCanadaMan",
        factor: 0.8466666666666667,
        offset: 18.626666666666665,
        symbol: "",
        name: "USA & Canada - Man",
        labelKey: "usaCanadaMan",
      },
      {
        id: "usaCanadaWoman",
        factor: 0.8466666666666667,
        offset: 17.78,
        symbol: "",
        name: "USA & Canada - Woman",
        labelKey: "usaCanadaWoman",
      },
      {
        id: "japan",
        factor: 1,
        offset: -1.5,
        symbol: "",
        name: "Japan",
        labelKey: "japan",
      },
    ],
  },
  {
    id: "digitalData",
    name: "Digital data",
    icon: "data",
    description: "Bits, bytes, and everything in between.",
    units: [
      {
        id: "bit",
        factor: 1,
        offset: 0,
        symbol: "b",
        name: "Bit",
        labelKey: "bit",
      },
      {
        id: "nibble",
        factor: 4.0,
        offset: 0,
        symbol: "",
        name: "Nibble",
        labelKey: "nibble",
      },
      {
        id: "kilobit",
        factor: 1000.0,
        offset: 0,
        symbol: "kb",
        name: "KiloBit",
        labelKey: "kilobit",
      },
      {
        id: "megabit",
        factor: 1000000.0,
        offset: 0,
        symbol: "Mb",
        name: "MegaBit",
        labelKey: "megabit",
      },
      {
        id: "gigabit",
        factor: 1000000000.0,
        offset: 0,
        symbol: "Gb",
        name: "GigaBit",
        labelKey: "gigabit",
      },
      {
        id: "terabit",
        factor: 1000000000000.0,
        offset: 0,
        symbol: "Tb",
        name: "TeraBit",
        labelKey: "terabit",
      },
      {
        id: "petabit",
        factor: 1000000000000000.0,
        offset: 0,
        symbol: "Pb",
        name: "PetaBit",
        labelKey: "petabit",
      },
      {
        id: "exabit",
        factor: 1e18,
        offset: 0,
        symbol: "Eb",
        name: "ExaBit",
        labelKey: "exabit",
      },
      {
        id: "kibibit",
        factor: 1024.0,
        offset: 0,
        symbol: "Kibit",
        name: "Kibibit",
        labelKey: "kibibit",
      },
      {
        id: "mebibit",
        factor: 1048576.0,
        offset: 0.0,
        symbol: "Mibit",
        name: "Mebibit",
        labelKey: "mebibit",
      },
      {
        id: "gibibit",
        factor: 1073741824.0,
        offset: 0.0,
        symbol: "Gibit",
        name: "GibiBit",
        labelKey: "gibibit",
      },
      {
        id: "tebibit",
        factor: 1099511627776.0,
        offset: 0.0,
        symbol: "Tibit",
        name: "Tebibit",
        labelKey: "tebibit",
      },
      {
        id: "pebibit",
        factor: 1125899906842624.0,
        offset: 0.0,
        symbol: "Pibit",
        name: "Pebibit",
        labelKey: "pebibit",
      },
      {
        id: "exbibit",
        factor: 1.152921504606847e18,
        offset: 0.0,
        symbol: "Eibit",
        name: "Exbibit",
        labelKey: "exbibit",
      },
      {
        id: "byte",
        factor: 8.0,
        offset: 0,
        symbol: "B",
        name: "Byte",
        labelKey: "byte",
      },
      {
        id: "kilobyte",
        factor: 8000.0,
        offset: 0.0,
        symbol: "kB",
        name: "KiloByte",
        labelKey: "kilobyte",
      },
      {
        id: "megabyte",
        factor: 8000000.0,
        offset: 0.0,
        symbol: "MB",
        name: "MegaByte",
        labelKey: "megabyte",
      },
      {
        id: "gigabyte",
        factor: 8000000000.0,
        offset: 0.0,
        symbol: "GB",
        name: "GigaByte",
        labelKey: "gigabyte",
      },
      {
        id: "terabyte",
        factor: 8000000000000.0,
        offset: 0.0,
        symbol: "TB",
        name: "TeraByte",
        labelKey: "terabyte",
      },
      {
        id: "petabyte",
        factor: 8000000000000000.0,
        offset: 0.0,
        symbol: "PB",
        name: "PetaByte",
        labelKey: "petabyte",
      },
      {
        id: "exabyte",
        factor: 8e18,
        offset: 0.0,
        symbol: "EB",
        name: "ExaByte",
        labelKey: "exabyte",
      },
      {
        id: "kibibyte",
        factor: 8192.0,
        offset: 0.0,
        symbol: "KiB",
        name: "Kibibyte",
        labelKey: "kibibyte",
      },
      {
        id: "mebibyte",
        factor: 8388608.0,
        offset: 0.0,
        symbol: "MiB",
        name: "Mebibyte",
        labelKey: "mebibyte",
      },
      {
        id: "gibibyte",
        factor: 8589934592.0,
        offset: 0.0,
        symbol: "GiB",
        name: "GibiByte",
        labelKey: "gibibyte",
      },
      {
        id: "tebibyte",
        factor: 8796093022208.0,
        offset: 0.0,
        symbol: "TiB",
        name: "Tebibyte",
        labelKey: "tebibyte",
      },
      {
        id: "pebibyte",
        factor: 9007199254740992.0,
        offset: 0.0,
        symbol: "PiB",
        name: "Pebibyte",
        labelKey: "pebibyte",
      },
      {
        id: "exbibyte",
        factor: 9.223372036854776e18,
        offset: 0.0,
        symbol: "EiB",
        name: "Exbibyte",
        labelKey: "exbibyte",
      },
    ],
  },
  {
    id: "siPrefixes",
    name: "SI prefixes",
    icon: "layers",
    description: "Think bigger. Or a little smaller.",
    units: [
      {
        id: "base",
        factor: 1,
        offset: 0,
        symbol: "",
        name: "Base",
        labelKey: "base",
      },
      {
        id: "deca",
        factor: 10.0,
        offset: 0,
        symbol: "da-",
        name: "Deca-",
        labelKey: "deca",
      },
      {
        id: "hecto",
        factor: 100.0,
        offset: 0,
        symbol: "h-",
        name: "Hecto-",
        labelKey: "hecto",
      },
      {
        id: "kilo",
        factor: 1000.0,
        offset: 0,
        symbol: "k-",
        name: "Kilo-",
        labelKey: "kilo",
      },
      {
        id: "mega",
        factor: 1000000.0,
        offset: 0,
        symbol: "M-",
        name: "Mega-",
        labelKey: "mega",
      },
      {
        id: "giga",
        factor: 1000000000.0,
        offset: 0,
        symbol: "G-",
        name: "Giga-",
        labelKey: "giga",
      },
      {
        id: "tera",
        factor: 1000000000000.0,
        offset: 0,
        symbol: "T-",
        name: "Tera-",
        labelKey: "tera",
      },
      {
        id: "peta",
        factor: 1000000000000000.0,
        offset: 0,
        symbol: "P-",
        name: "Peta-",
        labelKey: "peta",
      },
      {
        id: "exa",
        factor: 1e18,
        offset: 0,
        symbol: "E-",
        name: "Exa-",
        labelKey: "exa",
      },
      {
        id: "zetta",
        factor: 1e21,
        offset: 0,
        symbol: "Z-",
        name: "Zetta-",
        labelKey: "zetta",
      },
      {
        id: "yotta",
        factor: 1e24,
        offset: 0,
        symbol: "Y-",
        name: "Yotta-",
        labelKey: "yotta",
      },
      {
        id: "deci",
        factor: 0.1,
        offset: 0,
        symbol: "d-",
        name: "Deci-",
        labelKey: "deci",
      },
      {
        id: "centi",
        factor: 0.01,
        offset: 0,
        symbol: "c-",
        name: "Centi-",
        labelKey: "centi",
      },
      {
        id: "milli",
        factor: 0.001,
        offset: 0,
        symbol: "m-",
        name: "Milli-",
        labelKey: "milli",
      },
      {
        id: "micro",
        factor: 1e-6,
        offset: 0,
        symbol: "µ-",
        name: "Micro-",
        labelKey: "micro",
      },
      {
        id: "nano",
        factor: 1e-9,
        offset: 0,
        symbol: "n-",
        name: "Nano-",
        labelKey: "nano",
      },
      {
        id: "pico",
        factor: 1e-12,
        offset: 0,
        symbol: "p-",
        name: "Pico-",
        labelKey: "pico",
      },
      {
        id: "femto",
        factor: 1e-15,
        offset: 0,
        symbol: "f-",
        name: "Femto-",
        labelKey: "femto",
      },
      {
        id: "atto",
        factor: 1e-18,
        offset: 0,
        symbol: "a-",
        name: "Atto-",
        labelKey: "atto",
      },
      {
        id: "zepto",
        factor: 1e-21,
        offset: 0,
        symbol: "z-",
        name: "Zepto-",
        labelKey: "zepto",
      },
      {
        id: "yocto",
        factor: 1e-24,
        offset: 0,
        symbol: "y-",
        name: "Yocto-",
        labelKey: "yocto",
      },
      {
        id: "ronna",
        name: "Ronna",
        symbol: "R-",
        factor: 1000000000000000000000000000,
        offset: 0,
        labelKey: "ronna",
      },
      {
        id: "quetta",
        name: "Quetta",
        symbol: "Q-",
        factor: 1000000000000000000000000000000,
        offset: 0,
        labelKey: "quetta",
      },
      {
        id: "ronto",
        name: "Ronto",
        symbol: "r-",
        factor: 1e-27,
        offset: 0,
        labelKey: "ronto",
      },
      {
        id: "quecto",
        name: "Quecto",
        symbol: "q-",
        factor: 1e-30,
        offset: 0,
        labelKey: "quecto",
      },
    ],
  },
  {
    id: "torque",
    name: "Torque",
    icon: "rotate",
    description: "A different turn on measurement.",
    units: [
      {
        id: "newtonMeter",
        factor: 1,
        offset: 0,
        symbol: "N·m",
        name: "Newton meter",
        labelKey: "newtonMeter",
      },
      {
        id: "dyneMeter",
        factor: 1e-5,
        offset: 0,
        symbol: "dyn·m",
        name: "Dyne meter",
        labelKey: "dyneMeter",
      },
      {
        id: "poundForceFeet",
        factor: 1.3558179490249056,
        offset: 0,
        symbol: "lbf·ft",
        name: "Pound-force feet",
        labelKey: "poundForceFeet",
      },
      {
        id: "kilogramForceMeter",
        factor: 9.807,
        offset: 0,
        symbol: "kgf·m",
        name: "Kilogram-force meter",
        labelKey: "kilogramForceMeter",
      },
      {
        id: "poundalMeter",
        factor: 0.138254954376,
        offset: 0,
        symbol: "pdl·m",
        name: "Poundal meter",
        labelKey: "poundalMeter",
      },
    ],
  },
];
